modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="premod"
version="1.0.0"
displayName="pre117mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="user, MCreator"

[[dependencies.premod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




